import { trebuchet } from './Day1/trebuchet.js';
import { cubeConundrum } from './Day2/cubeConundrum.js';
import { gearRatios } from './Day3/gearRatios.js';
import { scratchcards } from './Day4/scratchcards.js';
import { fertilizer } from './Day5/fertilizer.js';
import { waitForIt } from './Day6/waitForIt.js';
import { camelCards } from './Day7/camelCards.js';
import { hauntedWasteland } from './Day8/hauntedWasteland.js';
import { mirageMaintenance } from './Day9/mirageMaintenance.js';
import { pipeMaze } from './Day10/pipeMaze.js';

// trebuchet();
// cubeConundrum();
// gearRatios();
// scratchcards();
// fertilizer();
// waitForIt();
// camelCards();
// hauntedWasteland();
// mirageMaintenance();
pipeMaze();
