import { trebuchet } from './Day1/trebuchet.js';
import { cubeConundrum } from './Day2/cubeConundrum.js';
import { gearRatios } from './Day3/gearRatios.js';
import { scratchcards } from './Day4/scratchcards.js';
import { fertilizer } from './Day5/fertilizer.js';
import { waitForIt } from './Day6/waitForIt.js';
import { camelCards } from './Day7/camelCards.js';
import { hauntedWasteland } from './Day8/hauntedWasteland.js';
import { mirageMaintenance } from './Day9/mirageMaintenance.js';
import { pipeMaze } from './Day10/pipeMaze.js';
import { cosmicExpansion } from './Day11/cosmicExpansion.js';
import { hotSprings } from './Day12/hotSprings.js';
import { pointOfIncidence } from './Day13/pointOfIncidence.js';
import { reflectorDish } from './Day14/reflectorDish.js';

// trebuchet();
// cubeConundrum();
// gearRatios();
// scratchcards();
// fertilizer();
// waitForIt();
// camelCards();
// hauntedWasteland();
// mirageMaintenance();
// pipeMaze();
// cosmicExpansion();
// hotSprings();
// pointOfIncidence();
reflectorDish();
